version: '3.8'

name: count-of-money-dev-services

services:
  api: 
    container_name: api
    build: 
      context: ../api
    env_file:
      - ./api/dev/.env
    ports:
      - 3000:3000
    volumes:
      - ../api:/app
    entrypoint: /app/entrypoint.sh
    depends_on:
      - database

  webapp:
    container_name: webapp
    build: 
      context: ../webapp
    env_file:
      - ./webapp/dev/.env
    ports:
      - 5173:5173   
    volumes:
      - ../webapp/:/app
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    entrypoint: /app/entrypoint.sh

  database:
    container_name: database
    image: postgres:alpine
    env_file:
      - ./database/dev/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes: 
  pgdata:
    name: "pgdata-dev"
