version: '3.8'

services:
  api: 
    container_name: api
    build: 
      context: ../api
      dockerfile: Api.Dockerfile
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
    volumes:
      - ../api:/app
    entrypoint: /app/entrypoint.sh
  
  database:
    container_name: database
    image: postgres:alpine
    env_file:
      - ./database/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes: 
  pgdata: